"""The contract version this package carries.

Its own module because it is the one declaration here that is not a type: it
names the FrameForge *document format* revision, which releases on a different
clock from the wheel (see `frameforge_api.__version__`).
"""
from __future__ import annotations


HEAD_VERSION = "2.11.0"  # v2 line; 2.11.0 makes DEPRECATION machine-readable: the three renderer-shortcut object types (circle/polygon/curve) and the superseded tokens.text_styles namespace carry the JSON Schema `deprecated` keyword, and the legacy KEYS — normalised by mode="before" validators, so absent from the schema as properties — are published as a registry under `x-frameforge-deprecations`. Annotation only: nothing validates differently, and backward compatibility means none of these forms can be removed inside the 2.x line. The revision moves because the emitted schema bytes do, and two different files claiming one revision is exactly the drift this contract is built to prevent. 2.10.0 adds the typographic rhythm layer and the ink cap 2.9.0 left open: BaselineGrid (defs.baseline_grid, RenderingContract.baseline_grid, Style.align_to_baseline), TextContract.measure, and ColorProfileDef.total_ink_limit — all optional, so strictly backward compatible. 2.9.0 widens the contract for print and bound work: typed colour (CmykColor/SpotColor/IccColor + defs.color_profiles), Style.overprint/overprint_mode, spine-relative PageMargin (inside/outside/gutter) + PageSide + canvas spreads, RubyInline/WarichuInline, and RenderTarget.output (format/dpi/colour/font-embedding/printer's marks) — every addition optional, every union extended, so it is strictly backward compatible. 2.4.0 adds the ordered per-object effect stack (`effects`) and the multi-pass appearance stack (`appearance`) — additive, outside the deep-core profile (§8.5, W4/#48). 2.3.0 added typed Connector, per-field schema descriptions, R12 referential integrity, Length/Angle value patterns (additive). 2.2.0 adopted the authoritative style module; P3 stroke collapse remains the one breaking change (codemod provided).
